// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFolder(name: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(3863529870, name);
}

export function CreateNote(): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(4174655258);
}

export function CreateNoteInFolder(folderID: string): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(2400960381, folderID);
}

export function EmptyTrash(): $CancellablePromise<[number, number]> {
    return $Call.ByID(2664781739);
}

export function GetRuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(3362057646).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IngestImage(content: Uint8Array, originalName: string): $CancellablePromise<string> {
    return $Call.ByID(3268997603, content, originalName);
}

export function ListFolderNotes(folderID: string): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(3400012691, folderID).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListFolders(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(3333458079).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListNotes(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(3334466307).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListRootNotes(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(1260630135).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListTrashFolderNotes(folderID: string): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(466940197, folderID).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListTrashFolders(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(903952433).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function ListTrashNotes(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(3893406897).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function MoveFolderToTrash(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(3096972676, folderID);
}

export function MoveNote(noteID: string, folderID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1994489847, noteID, folderID);
}

export function MoveNoteToTrash(noteID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1119408872, noteID);
}

export function OpenInitialNote(): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(2406348922);
}

export function OpenNote(noteID: string): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(2169568126, noteID);
}

export function OpenTrashNote(noteID: string): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(1480422420, noteID);
}

export function PermanentlyDeleteFolder(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(3774136408, folderID);
}

export function PermanentlyDeleteNote(noteID: string): $CancellablePromise<boolean> {
    return $Call.ByID(991217112, noteID);
}

export function RestoreFolder(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(953089364, folderID);
}

export function RestoreNote(noteID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2653971148, noteID);
}

export function SaveNote(noteID: string, title: string, documentJSON: string, expectedRevision: number): $CancellablePromise<number> {
    return $Call.ByID(1592610343, noteID, title, documentJSON, expectedRevision);
}

export function SearchNotes(query: string): $CancellablePromise<[string[], string[], string[]]> {
    return $Call.ByID(4172956135, query).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        $result[2] = $$createType1($result[2]);
        return $result;
    });
}

export function TrashCounts(): $CancellablePromise<[number, number]> {
    return $Call.ByID(2696325604);
}

// Private type creation functions
const $$createType0 = $models.RuntimeInfo.createFrom;
const $$createType1 = $Create.Array($Create.Any);
