// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateNote(): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(4174655258);
}

export function GetRuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(3362057646).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListNotes(): $CancellablePromise<[string[], string[]]> {
    return $Call.ByID(3334466307).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

export function OpenInitialNote(): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(2406348922);
}

export function OpenNote(noteID: string): $CancellablePromise<[string, string, string, number, boolean]> {
    return $Call.ByID(2169568126, noteID);
}

export function SaveNote(noteID: string, title: string, documentJSON: string, expectedRevision: number): $CancellablePromise<number> {
    return $Call.ByID(1592610343, noteID, title, documentJSON, expectedRevision);
}

// Private type creation functions
const $$createType0 = $models.RuntimeInfo.createFrom;
const $$createType1 = $Create.Array($Create.Any);
