// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportCurrentNoteMarkdown exports the exact admitted normal note as
 * Markdown. The note identity is bound by the frontend export gate before
 * the durability drain and passed in explicitly, so a concurrent note
 * transition cannot redirect this export via the persisted last-note
 * pointer at backend entry. Returning false with no error means the user
 * cancelled the dialog.
 */
export function ExportCurrentNoteMarkdown(admittedNoteID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3522548611, admittedNoteID);
}

/**
 * ExportLibraryMarkdown asks for a parent directory, then creates a new
 * collision-safe Flashnote Export directory containing every normal note.
 * Returning an empty path with no error means the user cancelled the dialog.
 */
export function ExportLibraryMarkdown(): $CancellablePromise<string> {
    return $Call.ByID(2014015777);
}
