// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportCurrentNoteMarkdown exports the exact normal note captured before the
 * native Save dialog opens. Returning false with no error means the user
 * cancelled the dialog.
 */
export function ExportCurrentNoteMarkdown(): $CancellablePromise<boolean> {
    return $Call.ByID(3522548611);
}
