// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RuntimeInfo {
    "appVersion": string;
    "databaseReady": boolean;
    "sqliteVersion": string;
    "journalMode": string;
    "synchronous": number;
    "foreignKeys": boolean;
    "schemaVersion": number;

    /** Creates a new RuntimeInfo instance. */
    constructor($$source: Partial<RuntimeInfo> = {}) {
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("databaseReady" in $$source)) {
            this["databaseReady"] = false;
        }
        if (!("sqliteVersion" in $$source)) {
            this["sqliteVersion"] = "";
        }
        if (!("journalMode" in $$source)) {
            this["journalMode"] = "";
        }
        if (!("synchronous" in $$source)) {
            this["synchronous"] = 0;
        }
        if (!("foreignKeys" in $$source)) {
            this["foreignKeys"] = false;
        }
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeInfo($$parsedSource as Partial<RuntimeInfo>);
    }
}
